# Generated by Django 3.2 on 2023-02-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seaporttransaction',
            name='tx_input',
            field=models.TextField(null=True),
        ),
    ]
