# Generated by Django 3.2 on 2023-02-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0002_seaporttransaction_tx_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seaporttransaction',
            name='gas_used',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seaporttransaction',
            name='tx_fee',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seaporttransaction',
            name='value',
            field=models.BigIntegerField(default=0),
        ),
    ]
