# Generated by Django 3.2 on 2023-02-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0004_alter_seaporttransaction_gas_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seaporttransaction',
            name='value',
            field=models.DecimalField(decimal_places=0, max_digits=65),
        ),
    ]
