# Generated by Django 3.2 on 2023-02-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0005_alter_seaporttransaction_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seaporttransaction',
            name='method_name',
            field=models.CharField(max_length=256),
        ),
    ]
