# Generated by Django 3.2 on 2023-02-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0006_alter_seaporttransaction_method_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seaporttransaction',
            name='volumes',
            field=models.TextField(null=True),
        ),
    ]
