# Generated by Django 3.2 on 2023-02-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0007_seaporttransaction_volumes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seaporttransaction',
            name='tx_input',
        ),
    ]
