# Generated by Django 3.2 on 2023-02-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0008_remove_seaporttransaction_tx_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seaporttransaction',
            name='token_contract_address',
        ),
        migrations.RemoveField(
            model_name='seaporttransaction',
            name='token_id',
        ),
    ]
