# Generated by Django 3.2 on 2023-02-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0009_auto_20230228_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seaport1155Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=100)),
                ('contract_address', models.CharField(blank=True, max_length=100, null=True)),
                ('token_id', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField()),
                ('matic_price', models.DecimalField(decimal_places=0, max_digits=65)),
                ('usdc_price', models.DecimalField(decimal_places=0, max_digits=65)),
                ('weth_price', models.DecimalField(decimal_places=0, max_digits=65)),
                ('spot_price', models.DecimalField(decimal_places=0, max_digits=65)),
                ('buyer', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'seaport_1155_transaction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seaport721Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=100)),
                ('contract_address', models.CharField(blank=True, max_length=100, null=True)),
                ('token_id', models.CharField(blank=True, max_length=100, null=True)),
                ('matic_price', models.DecimalField(decimal_places=0, max_digits=65)),
                ('usdc_price', models.DecimalField(decimal_places=0, max_digits=65)),
                ('weth_price', models.DecimalField(decimal_places=0, max_digits=65)),
                ('spot_price', models.DecimalField(decimal_places=0, max_digits=65)),
                ('buyer', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'seaport_721_transaction',
                'managed': True,
            },
        ),
    ]
