# Generated by Django 3.2 on 2023-02-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0010_seaport1155transaction_seaport721transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seaport1155transaction',
            name='quantity',
            field=models.BigIntegerField(),
        ),
    ]
