# Generated by Django 3.2 on 2023-02-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0011_alter_seaport1155transaction_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seaport1155transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=65),
        ),
    ]
