# Generated by Django 3.2 on 2023-03-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0012_alter_seaport1155transaction_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seaporttransaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='seaporttransaction',
            name='tx_hash',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
