# Generated by Django 3.2 on 2023-03-01 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0013_auto_20230301_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seaport1155transaction',
            name='tx_hash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nft.seaporttransaction'),
        ),
        migrations.AlterField(
            model_name='seaport721transaction',
            name='tx_hash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nft.seaporttransaction'),
        ),
    ]
