# Generated by Django 3.2 on 2023-03-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0014_auto_20230301_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(max_length=16)),
                ('price', models.FloatField()),
            ],
        ),
    ]
